# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, TYPE_CHECKING

from azure.core import PipelineClient
from azure.core.rest import HttpRequest, HttpResponse

from ._configuration import EasmClientConfiguration
from ._serialization import Deserializer, Serializer
from .operations import (
    AssetsOperations,
    DataConnectionsOperations,
    DiscoveryGroupsOperations,
    DiscoveryTemplatesOperations,
    ReportsOperations,
    SavedFiltersOperations,
    TasksOperations,
)

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials import TokenCredential


class EasmClient:  # pylint: disable=client-accepts-api-version-keyword,too-many-instance-attributes
    """Defender EASM discovers and maps your digital attack surface to provide an "outside-in"
    perspective using probes to discover assets. The assets are provided with detailed metadata
    associated, including vulnerabilities, configurations and web components, allowing customers to
    view and prioritize external risk. The EASM REST API enables you to develop clients that
    integrate with your application.

    :ivar assets: AssetsOperations operations
    :vartype assets: azure.easm.operations.AssetsOperations
    :ivar data_connections: DataConnectionsOperations operations
    :vartype data_connections: azure.easm.operations.DataConnectionsOperations
    :ivar discovery_groups: DiscoveryGroupsOperations operations
    :vartype discovery_groups: azure.easm.operations.DiscoveryGroupsOperations
    :ivar discovery_templates: DiscoveryTemplatesOperations operations
    :vartype discovery_templates: azure.easm.operations.DiscoveryTemplatesOperations
    :ivar reports: ReportsOperations operations
    :vartype reports: azure.easm.operations.ReportsOperations
    :ivar saved_filters: SavedFiltersOperations operations
    :vartype saved_filters: azure.easm.operations.SavedFiltersOperations
    :ivar tasks: TasksOperations operations
    :vartype tasks: azure.easm.operations.TasksOperations
    :param subscription_id: The ID of the target subscription. Required.
    :type subscription_id: str
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials.TokenCredential
    :param region: The region hosting the requested resource. Default value is "api".
    :type region: str
    :keyword api_version: Api Version. Default value is "2022-09-01-preview". Note that overriding
     this default value may result in unsupported behavior.
    :paramtype api_version: str
    """

    def __init__(self, subscription_id: str, credential: "TokenCredential", region: str = "api", **kwargs: Any) -> None:
        _endpoint = "https://{region}.easm.defender.microsoft.com"
        self._config = EasmClientConfiguration(
            subscription_id=subscription_id, credential=credential, region=region, **kwargs
        )
        self._client = PipelineClient(base_url=_endpoint, config=self._config, **kwargs)

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False
        self.assets = AssetsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.data_connections = DataConnectionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.discovery_groups = DiscoveryGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.discovery_templates = DiscoveryTemplatesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.reports = ReportsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.saved_filters = SavedFiltersOperations(self._client, self._config, self._serialize, self._deserialize)
        self.tasks = TasksOperations(self._client, self._config, self._serialize, self._deserialize)

    def send_request(self, request: HttpRequest, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client.send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        path_format_arguments = {
            "region": self._serialize.url("self._config.region", self._config.region, "str"),
        }

        request_copy.url = self._client.format_url(request_copy.url, **path_format_arguments)
        return self._client.send_request(request_copy, **kwargs)

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "EasmClient":
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details) -> None:
        self._client.__exit__(*exc_details)
