# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import ErrorAdditionalInfo
from ._models import ErrorDetail
from ._models import ErrorResponse
from ._models import LabelPatchResource
from ._models import LabelResource
from ._models import LabelResourceProperties
from ._models import Operation
from ._models import OperationDisplay
from ._models import ProxyResource
from ._models import Resource
from ._models import ResourceBaseProperties
from ._models import SystemData
from ._models import TrackedResource
from ._models import WorkspacePatchResource
from ._models import WorkspaceResource

from ._enums import ActionType
from ._enums import CreatedByType
from ._enums import Origin
from ._enums import ResourceState
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "ErrorAdditionalInfo",
    "ErrorDetail",
    "ErrorResponse",
    "LabelPatchResource",
    "LabelResource",
    "LabelResourceProperties",
    "Operation",
    "OperationDisplay",
    "ProxyResource",
    "Resource",
    "ResourceBaseProperties",
    "SystemData",
    "TrackedResource",
    "WorkspacePatchResource",
    "WorkspaceResource",
    "ActionType",
    "CreatedByType",
    "Origin",
    "ResourceState",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
