# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AssetLabelRequestTransfers(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """A list of asset types to cascade the updates to."""

    AS = "as"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_ADDRESS = "ipAddress"
    IP_BLOCK = "ipBlock"
    PAGE = "page"
    SSL_CERT = "sslCert"


class AssetResponseKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The kind of asset."""

    AS = "as"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_ADDRESS = "ipAddress"
    IP_BLOCK = "ipBlock"
    PAGE = "page"
    SSL_CERT = "sslCert"


class AssetResponseState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AssetResponseState."""

    CANDIDATE = "candidate"
    CONFIRMED = "confirmed"
    DISMISSED = "dismissed"
    CANDIDATE_INVESTIGATE = "candidateInvestigate"
    ASSOCIATED_PARTNER = "associatedPartner"
    ASSOCIATED_THIRDPARTY = "associatedThirdparty"
    ARCHIVED = "archived"


class AssetUpdateRequestState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The state to update the asset to."""

    CANDIDATE = "candidate"
    CONFIRMED = "confirmed"
    DISMISSED = "dismissed"
    CANDIDATE_INVESTIGATE = "candidateInvestigate"
    ASSOCIATED_PARTNER = "associatedPartner"
    ASSOCIATED_THIRDPARTY = "associatedThirdparty"


class AuditTrailItemKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The kind of asset."""

    AS = "as"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_ADDRESS = "ipAddress"
    IP_BLOCK = "ipBlock"
    PAGE = "page"
    SSL_CERT = "sslCert"


class DataConnectionRequestKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The kind of data connection."""

    SENTINEL = "sentinel"


class DataConnectionResponseKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The kind of data connection."""

    SENTINEL = "sentinel"


class DiscoRunResponseState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The State of the disco run."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class DiscoSourceKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The kind of disco source."""

    AS = "as"
    ATTRIBUTE = "attribute"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_BLOCK = "ipBlock"


class ObservedPortStateValue(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ObservedPortStateValue."""

    OPEN = "open"
    CLOSED = "closed"
    FILTERED = "filtered"


class PageAssetRedirectType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PageAssetRedirectType."""

    HTTP_HEADER = "httpHeader"
    META_REFRESH = "metaRefresh"
    JAVASCRIPT = "javascript"
    FINAL = "final"


class SslCertAssetValidationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """SslCertAssetValidationType."""

    DOMAIN_VALIDATION = "domainValidation"
    ORGANIZATION_VALIDATION = "organizationValidation"
    EXTENDED_VALIDATION = "extendedValidation"


class TaskResponsePhase(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """TaskResponsePhase."""

    RUNNING = "running"
    POLLING = "polling"
    COMPLETE = "complete"


class TaskResponseState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """TaskResponseState."""

    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETE = "complete"
    INCOMPLETE = "incomplete"
    FAILED = "failed"
    WARNING = "warning"
